// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.14.0
// source: sql_info.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SQLInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SqlText       string                 `protobuf:"bytes,1,opt,name=sql_text,json=sqlText,proto3" json:"sql_text,omitempty"`
	TxnId         int32                  `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	RegionIds     []int32                `protobuf:"varint,3,rep,packed,name=region_ids,json=regionIds,proto3" json:"region_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLInfoRequest) Reset() {
	*x = SQLInfoRequest{}
	mi := &file_sql_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLInfoRequest) ProtoMessage() {}

func (x *SQLInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sql_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLInfoRequest.ProtoReflect.Descriptor instead.
func (*SQLInfoRequest) Descriptor() ([]byte, []int) {
	return file_sql_info_proto_rawDescGZIP(), []int{0}
}

func (x *SQLInfoRequest) GetSqlText() string {
	if x != nil {
		return x.SqlText
	}
	return ""
}

func (x *SQLInfoRequest) GetTxnId() int32 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *SQLInfoRequest) GetRegionIds() []int32 {
	if x != nil {
		return x.RegionIds
	}
	return nil
}

type SQLInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLInfoResponse) Reset() {
	*x = SQLInfoResponse{}
	mi := &file_sql_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLInfoResponse) ProtoMessage() {}

func (x *SQLInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sql_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLInfoResponse.ProtoReflect.Descriptor instead.
func (*SQLInfoResponse) Descriptor() ([]byte, []int) {
	return file_sql_info_proto_rawDescGZIP(), []int{1}
}

func (x *SQLInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sql_info_proto protoreflect.FileDescriptor

var file_sql_info_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x71, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x61, 0x0a, 0x0e, 0x53, 0x51, 0x4c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x71, 0x6c, 0x5f, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x71, 0x6c, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x51, 0x4c, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x32, 0x48, 0x0a, 0x0e, 0x53, 0x51, 0x4c, 0x49, 0x6e, 0x66, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x51,
	0x4c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x51, 0x4c, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x51, 0x4c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30,
	0x5a, 0x2e, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x7a, 0x71, 0x73, 0x2f, 0x74, 0x69, 0x64, 0x62,
	0x2d, 0x38, 0x2e, 0x35, 0x2e, 0x30, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x2f,
	0x6c, 0x69, 0x6f, 0x6e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sql_info_proto_rawDescOnce sync.Once
	file_sql_info_proto_rawDescData = file_sql_info_proto_rawDesc
)

func file_sql_info_proto_rawDescGZIP() []byte {
	file_sql_info_proto_rawDescOnce.Do(func() {
		file_sql_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_sql_info_proto_rawDescData)
	})
	return file_sql_info_proto_rawDescData
}

var file_sql_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sql_info_proto_goTypes = []any{
	(*SQLInfoRequest)(nil),  // 0: pb.SQLInfoRequest
	(*SQLInfoResponse)(nil), // 1: pb.SQLInfoResponse
}
var file_sql_info_proto_depIdxs = []int32{
	0, // 0: pb.SQLInfoService.SendSQLInfo:input_type -> pb.SQLInfoRequest
	1, // 1: pb.SQLInfoService.SendSQLInfo:output_type -> pb.SQLInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sql_info_proto_init() }
func file_sql_info_proto_init() {
	if File_sql_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sql_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sql_info_proto_goTypes,
		DependencyIndexes: file_sql_info_proto_depIdxs,
		MessageInfos:      file_sql_info_proto_msgTypes,
	}.Build()
	File_sql_info_proto = out.File
	file_sql_info_proto_rawDesc = nil
	file_sql_info_proto_goTypes = nil
	file_sql_info_proto_depIdxs = nil
}
