# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sql_info.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'sql_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esql_info.proto\x12\x02pb\"T\n\x0eSQLInfoRequest\x12\x10\n\x08sql_text\x18\x01 \x01(\t\x12\x0e\n\x06txn_id\x18\x02 \x01(\x05\x12\x0c\n\x04keys\x18\x03 \x03(\x05\x12\x12\n\nregion_ids\x18\x04 \x03(\x05\"\"\n\x0fSQLInfoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32H\n\x0eSQLInfoService\x12\x36\n\x0bSendSQLInfo\x12\x12.pb.SQLInfoRequest\x1a\x13.pb.SQLInfoResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sql_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_SQLINFOREQUEST']._serialized_start=22
  _globals['_SQLINFOREQUEST']._serialized_end=106
  _globals['_SQLINFORESPONSE']._serialized_start=108
  _globals['_SQLINFORESPONSE']._serialized_end=142
  _globals['_SQLINFOSERVICE']._serialized_start=144
  _globals['_SQLINFOSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
